Feature/custom push
Innim/flutter_local_notifications pull request #1
Opened 2021-05-06 12:42 UTC by SF-97

As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_local_notifications])

2021-05-06 13:06 UTC, greymag requested changes

2021-05-06 13:06 UTC, greymag commented on flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
> +  final String customNotificationPackageName;
А это общие настройки  или настройка конкретного оповещения? Пакет же по идее единый?

2021-05-06 13:06 UTC, greymag commented on flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
> +  /// located in the `layout` directory of the android application.
Получается только 1 лейаут поддерживается? По идее должно быть сколько угодно, я просто 1 раз на приложение указываю PackageName и для конкретного оповещения имя лейаута, и юзаю. Потому что может быть одно оповещение с одним леайутом, а другое - с другим.

2021-05-06 13:06 UTC, greymag commented on flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
> +  /// Specifies the custom notification package.
По доке не очень понятно что это и откуда взять

2021-05-06 13:06 UTC, greymag commented on flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
> +                e.printStackTrace();
Тут получается что код дальше пойдет и упадет на null

2021-05-06 13:38 UTC, SF-97 commented on flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
> +  final String customNotificationPackageName;
По идее для всех. Параметр указывается в AndroidNotificationDetails

2021-05-06 14:50 UTC, SF-97 commented on flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
> +  final String customNotificationPackageName;
Переделал, теперь указывается один раз при инициализации плагина

2021-05-06 14:50 UTC, SF-97 commented on flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
> +  /// located in the `layout` directory of the android application.
Так и сделал

2021-05-06 14:50 UTC, SF-97 commented on flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
> +                e.printStackTrace();
Поправил

2021-05-06 15:00 UTC, SF-97 commented on flutter_local_notifications/lib/src/platform_specifics/android/notification_details.dart
> +  /// Specifies the custom notification package.
Дописал

2021-05-07 08:21 UTC, greymag requested changes

2021-05-07 08:21 UTC, greymag commented on flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
> +            editor.putString(PACKAGE_NAME, packageName);
Тут видимо в любом случае надо записывать, иначе если у нас был PACKAGE_NAME, а при след. запуске он был сброшен, то у тебя останется старый

2021-05-07 08:21 UTC, greymag commented on flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
> +            String packageName = sharedPreferences.getString(PACKAGE_NAME, null);
А давай попробуем получить имя пакета через контекст, без передачи из dart части

2021-05-07 08:30 UTC, SF-97 commented on flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
> +            editor.putString(PACKAGE_NAME, packageName);
Выпилил беру из контекста

2021-05-07 08:31 UTC, SF-97 commented on flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
> +            String packageName = sharedPreferences.getString(PACKAGE_NAME, null);
Получилось

2021-05-07 09:28 UTC, greymag approved these changes

2021-05-07 09:28 UTC, merged